# Generated by Django 4.1.4 on 2022-12-30 14:34

from django.db import migrations, models


class Migration(migrations.Migration):
    """
        --
        -- Create model TestsDetails
        --
        CREATE TABLE "tests_app_testsdetails" ("id" integer NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, "name" varchar(500) NULL, "total_questions" integer NOT NULL, "question_details" jsonb NOT NULL);
    """
    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TestsDetails',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=500, null=True)),
                ('total_questions', models.IntegerField(default=0)),
                ('question_details', models.JSONField(max_length=20000)),
            ],
        ),
    ]
