# Generated by Django 3.1.7 on 2023-04-13 11:05

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests_app', '0002_testsdetails_is_active'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestAllocations',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500, null=True)),
                ('key', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('start_date', models.DateTimeField(auto_now_add=True)),
                ('end_date', models.DateTimeField()),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='test_allocations', to='tests_app.testsdetails')),
            ],
        ),
        migrations.CreateModel(
            name='UserTests',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=500, null=True)),
                ('test_allocation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_tests', to='tests_app.testallocations')),
            ],
        ),
    ]
