# Generated by Django 3.1.7 on 2023-05-23 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests_app', '0003_testallocations_usertests'),
    ]

    operations = [
        migrations.AddField(
            model_name='usertests',
            name='first_name',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='usertests',
            name='last_name',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
