# Generated by Django 3.1.7 on 2023-06-21 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests_app', '0004_auto_20230523_0645'),
    ]

    operations = [
        migrations.AddField(
            model_name='usertests',
            name='completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='usertests',
            name='correct_answers',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='usertests',
            name='generated_question',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='usertests',
            name='score',
            field=models.IntegerField(default=0),
        ),
    ]
