# Generated by Django 3.1.7 on 2023-06-26 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests_app', '0005_auto_20230621_0453'),
    ]

    operations = [
        migrations.AddField(
            model_name='usertests',
            name='submission_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
