# Generated by Django 3.1.7 on 2023-06-30 05:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tests_app', '0006_usertests_submission_date'),
        ('tests_app', '0005_usertests_captured_image_locations'),
    ]

    operations = [
    ]
