# Generated by Django 3.1.7 on 2023-07-05 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests_app', '0006_usertests_submission_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='testsdetails',
            name='duration',
            field=models.DurationField(null=True),
        ),
    ]
