# Generated by Django 3.1.7 on 2023-06-30 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests_app', '0007_merge_20230630_0541'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usertests',
            name='captured_image_locations',
            field=models.JSONField(default=list, max_length=10000, null=True),
        ),
    ]
