# Generated by Django 3.1.7 on 2023-08-30 06:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tests_app', '0007_testsdetails_duration'),
        ('tests_app', '0008_auto_20230630_0548'),
    ]

    operations = [
    ]
