# Generated by Django 3.1.7 on 2023-08-30 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests_app', '0009_merge_20230830_0658'),
    ]

    operations = [
        migrations.AddField(
            model_name='testsdetails',
            name='weightage',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
