# Generated by Django 3.1.7 on 2023-09-01 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests_app', '0010_testsdetails_weightage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usertests',
            name='score',
            field=models.FloatField(default=0),
        ),
    ]
