# Generated by Django 3.1.7 on 2024-02-05 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests_app', '0011_auto_20230901_0640'),
    ]

    operations = [
        migrations.AddField(
            model_name='testsdetails',
            name='end_date',
            field=models.DateTimeField(null=True),
        ),
    ]
