# Generated by Django 3.1.7 on 2024-02-06 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests_app', '0013_auto_20240205_1653'),
    ]

    operations = [
        migrations.AddField(
            model_name='testsdetails',
            name='add_section',
            field=models.JSONField(default=[], max_length=20000),
        ),
    ]
