# Generated by Django 3.1.7 on 2024-02-06 09:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tests_app', '0014_testsdetails_add_section'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='testsdetails',
            name='add_section',
        ),
    ]
