# Generated by Django 3.1.7 on 2024-02-06 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests_app', '0015_remove_testsdetails_add_section'),
    ]

    operations = [
        migrations.AddField(
            model_name='testallocations',
            name='email_list',
            field=models.TextField(null=True),
        ),
    ]
