# Generated by Django 3.1.7 on 2023-02-10 13:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    """
        BEGIN;
            --
            -- Create model Question
            --
            CREATE TABLE "questions_question" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "name" varchar(5000) NOT NULL, "type" integer NOT NULL, "difficulty" integer NOT NULL, "language" varchar(500) NULL);
            --
            -- Create model ProgramTestCase
            --
            CREATE TABLE "questions_programtestcase" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "case1" varchar(5000) NULL, "case2" varchar(5000) NULL, "case3" varchar(5000) NULL, "case4" varchar(5000) NULL, "question_id" integer NOT NULL REFERENCES "questions_question" ("id") DEFERRABLE INITIALLY DEFERRED);
            --
            -- Create model MultipleChoicesAnswer
            --
            CREATE TABLE "questions_multiplechoicesanswer" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "option1" varchar(5000) NULL, "option2" varchar(5000) NULL, "option3" varchar(5000) NULL, "option4" varchar(5000) NULL, "correct_value" varchar(5000) NULL, "question_id" integer NOT NULL REFERENCES "questions_question" ("id") DEFERRABLE INITIALLY DEFERRED);
            CREATE INDEX "questions_programtestcase_question_id_ad0a98d8" ON "questions_programtestcase" ("question_id");
            CREATE INDEX "questions_multiplechoicesanswer_question_id_2824c0a4" ON "questions_multiplechoicesanswer" ("question_id");
        COMMIT;
    """


    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=5000)),
                ('type', models.IntegerField(choices=[(1, 'Multiple Choices'), (2, 'Programs')], default=1)),
                ('difficulty', models.IntegerField(choices=[(1, 'Easy'), (2, 'Medium'), (3, 'Hard')], default=1)),
                ('language', models.CharField(max_length=500, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProgramTestCase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('case1', models.CharField(max_length=5000, null=True)),
                ('case2', models.CharField(max_length=5000, null=True)),
                ('case3', models.CharField(max_length=5000, null=True)),
                ('case4', models.CharField(max_length=5000, null=True)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='program_test_cases', to='questions.question')),
            ],
        ),
        migrations.CreateModel(
            name='MultipleChoicesAnswer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('option1', models.CharField(max_length=5000, null=True)),
                ('option2', models.CharField(max_length=5000, null=True)),
                ('option3', models.CharField(max_length=5000, null=True)),
                ('option4', models.CharField(max_length=5000, null=True)),
                ('correct_value', models.CharField(max_length=5000, null=True)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='muliple_choice_answers', to='questions.question')),
            ],
        ),
    ]
