# repos:
#   - repo: local
#     hooks:
#       - id: pytest-check
#         name: pytest-check
#         entry: bash -c "source .venv/Scripts/activate && pytest nitoronlinetestportal/ && deactivate"
#         language: python
#         pass_filenames: false
#         always_run: true

repos:
  - repo: local
    hooks:
      - id: pytest-check
        name: pytest-check
        entry: "./.venv/Scripts/activate"
        language: system
        pass_filenames: false
        always_run: true

